name: 3hgj_orbit
description: A sample dartemis application
dependencies:
  browser: any
  canvas_query: any
  dartemis_toolbox: any
  gamedev_helpers:
    git: https://github.com/denniskaselow/gamedev_helpers
  vector_math: any
